/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const PostId = IDL.Text;
export const Time = IDL.Int;
export const Comment = IDL.Record({
  'content' : IDL.Text,
  'createdAt' : Time,
  'author' : IDL.Text,
});
export const Review = IDL.Record({
  'author' : IDL.Text,
  'comment' : IDL.Text,
  'timestamp' : Time,
  'rating' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const BlueprintTheme = IDL.Record({
  'primaryColor' : IDL.Text,
  'accentColor' : IDL.Text,
  'bannerImage' : IDL.Opt(ExternalBlob),
  'secondaryColor' : IDL.Text,
});
export const CreatorId = IDL.Principal;
export const MarketplaceBlueprint = IDL.Record({
  'id' : IDL.Text,
  'theme' : BlueprintTheme,
  'creator' : CreatorId,
  'createdAt' : Time,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'isFree' : IDL.Bool,
  'image' : IDL.Opt(ExternalBlob),
  'price' : IDL.Nat,
});
export const Post = IDL.Record({
  'id' : PostId,
  'content' : IDL.Text,
  'createdAt' : Time,
  'likedBy' : IDL.Vec(IDL.Principal),
  'author' : IDL.Text,
  'likes' : IDL.Nat,
  'image' : IDL.Opt(ExternalBlob),
  'comments' : IDL.Nat,
  'attachedBlueprintId' : IDL.Opt(IDL.Text),
});
export const Block = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'order' : IDL.Nat,
  'blockType' : IDL.Text,
  'options' : IDL.Vec(IDL.Text),
});
export const StepView = IDL.Record({
  'id' : IDL.Text,
  'order' : IDL.Nat,
  'name' : IDL.Text,
  'blocks' : IDL.Vec(Block),
});
export const ProjectBlueprintView = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'createdBy' : IDL.Principal,
  'steps' : IDL.Vec(StepView),
});
export const Blueprint = IDL.Record({
  'id' : IDL.Text,
  'theme' : BlueprintTheme,
  'active' : IDL.Bool,
  'createdAt' : Time,
  'calorieGoal' : IDL.Float64,
  'weeks' : IDL.Nat,
  'poundsToLose' : IDL.Float64,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'completedTasks' : IDL.Vec(Time),
  'banner' : IDL.Opt(ExternalBlob),
  'followers' : IDL.Nat,
  'following' : IDL.Nat,
  'hasCompletedSetup' : IDL.Bool,
  'avatar' : IDL.Opt(ExternalBlob),
});
export const DailyTask = IDL.Record({
  'waterIntake' : IDL.Bool,
  'date' : Time,
  'caloriesLogged' : IDL.Bool,
  'weighIn' : IDL.Bool,
  'stepsCompleted' : IDL.Bool,
  'workoutComplete' : IDL.Bool,
});
export const Message = IDL.Record({
  'content' : IDL.Text,
  'sender' : IDL.Text,
  'timestamp' : Time,
});
export const OwnerId = IDL.Principal;
export const OwnershipRecord = IDL.Record({
  'purchaseTime' : Time,
  'owner' : OwnerId,
  'blueprintId' : IDL.Text,
});
export const Progress = IDL.Record({
  'streak' : IDL.Nat,
  'goalWeight' : IDL.Float64,
  'currentWeight' : IDL.Float64,
  'checkpointsCompleted' : IDL.Nat,
});
export const UserId = IDL.Principal;
export const Reaction = IDL.Record({
  'userId' : UserId,
  'reactionType' : IDL.Variant({
    'sad' : IDL.Null,
    'wow' : IDL.Null,
    'angry' : IDL.Null,
    'haha' : IDL.Null,
    'like' : IDL.Null,
    'love' : IDL.Null,
  }),
  'timestamp' : Time,
  'postId' : PostId,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const WeightEntry = IDL.Record({
  'weight' : IDL.Float64,
  'date' : Time,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([PostId, Comment], [], []),
  'addReaction' : IDL.Func(
      [
        PostId,
        IDL.Variant({
          'sad' : IDL.Null,
          'wow' : IDL.Null,
          'angry' : IDL.Null,
          'haha' : IDL.Null,
          'like' : IDL.Null,
          'love' : IDL.Null,
        }),
      ],
      [],
      [],
    ),
  'addReview' : IDL.Func([IDL.Text, Review], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createMarketplaceBlueprint' : IDL.Func([MarketplaceBlueprint], [], []),
  'createPost' : IDL.Func([Post], [], []),
  'createProjectBlueprint' : IDL.Func([ProjectBlueprintView], [], []),
  'deletePost' : IDL.Func([PostId], [], []),
  'followUser' : IDL.Func([IDL.Principal], [], []),
  'getBlueprint' : IDL.Func([], [IDL.Opt(Blueprint)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getComments' : IDL.Func([PostId], [IDL.Vec(Comment)], ['query']),
  'getDailyTasks' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(Time, DailyTask))],
      ['query'],
    ),
  'getFollowers' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'getMarketplaceBlueprint' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(MarketplaceBlueprint)],
      ['query'],
    ),
  'getMarketplaceBlueprints' : IDL.Func(
      [],
      [IDL.Vec(MarketplaceBlueprint)],
      ['query'],
    ),
  'getMessages' : IDL.Func([IDL.Text], [IDL.Vec(Message)], ['query']),
  'getOwnedBlueprints' : IDL.Func([], [IDL.Vec(OwnershipRecord)], ['query']),
  'getPost' : IDL.Func([PostId], [IDL.Opt(Post)], ['query']),
  'getPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getProgress' : IDL.Func([], [IDL.Opt(Progress)], ['query']),
  'getProjectBlueprints' : IDL.Func(
      [],
      [IDL.Vec(ProjectBlueprintView)],
      ['query'],
    ),
  'getReactions' : IDL.Func([PostId], [IDL.Vec(Reaction)], ['query']),
  'getReviews' : IDL.Func([IDL.Text], [IDL.Vec(Review)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWeightEntries' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(Time, WeightEntry))],
      ['query'],
    ),
  'initializeLikedBy' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'likePost' : IDL.Func([PostId], [], []),
  'purchaseBlueprint' : IDL.Func([IDL.Text], [], []),
  'saveBlueprint' : IDL.Func([Blueprint], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveDailyTask' : IDL.Func([Time, DailyTask], [], []),
  'saveProgress' : IDL.Func([Progress], [], []),
  'saveWeightEntry' : IDL.Func([WeightEntry], [], []),
  'sendMessage' : IDL.Func([IDL.Text, Message], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'unfollowUser' : IDL.Func([IDL.Principal], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const PostId = IDL.Text;
  const Time = IDL.Int;
  const Comment = IDL.Record({
    'content' : IDL.Text,
    'createdAt' : Time,
    'author' : IDL.Text,
  });
  const Review = IDL.Record({
    'author' : IDL.Text,
    'comment' : IDL.Text,
    'timestamp' : Time,
    'rating' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const BlueprintTheme = IDL.Record({
    'primaryColor' : IDL.Text,
    'accentColor' : IDL.Text,
    'bannerImage' : IDL.Opt(ExternalBlob),
    'secondaryColor' : IDL.Text,
  });
  const CreatorId = IDL.Principal;
  const MarketplaceBlueprint = IDL.Record({
    'id' : IDL.Text,
    'theme' : BlueprintTheme,
    'creator' : CreatorId,
    'createdAt' : Time,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'isFree' : IDL.Bool,
    'image' : IDL.Opt(ExternalBlob),
    'price' : IDL.Nat,
  });
  const Post = IDL.Record({
    'id' : PostId,
    'content' : IDL.Text,
    'createdAt' : Time,
    'likedBy' : IDL.Vec(IDL.Principal),
    'author' : IDL.Text,
    'likes' : IDL.Nat,
    'image' : IDL.Opt(ExternalBlob),
    'comments' : IDL.Nat,
    'attachedBlueprintId' : IDL.Opt(IDL.Text),
  });
  const Block = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'order' : IDL.Nat,
    'blockType' : IDL.Text,
    'options' : IDL.Vec(IDL.Text),
  });
  const StepView = IDL.Record({
    'id' : IDL.Text,
    'order' : IDL.Nat,
    'name' : IDL.Text,
    'blocks' : IDL.Vec(Block),
  });
  const ProjectBlueprintView = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'createdBy' : IDL.Principal,
    'steps' : IDL.Vec(StepView),
  });
  const Blueprint = IDL.Record({
    'id' : IDL.Text,
    'theme' : BlueprintTheme,
    'active' : IDL.Bool,
    'createdAt' : Time,
    'calorieGoal' : IDL.Float64,
    'weeks' : IDL.Nat,
    'poundsToLose' : IDL.Float64,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'completedTasks' : IDL.Vec(Time),
    'banner' : IDL.Opt(ExternalBlob),
    'followers' : IDL.Nat,
    'following' : IDL.Nat,
    'hasCompletedSetup' : IDL.Bool,
    'avatar' : IDL.Opt(ExternalBlob),
  });
  const DailyTask = IDL.Record({
    'waterIntake' : IDL.Bool,
    'date' : Time,
    'caloriesLogged' : IDL.Bool,
    'weighIn' : IDL.Bool,
    'stepsCompleted' : IDL.Bool,
    'workoutComplete' : IDL.Bool,
  });
  const Message = IDL.Record({
    'content' : IDL.Text,
    'sender' : IDL.Text,
    'timestamp' : Time,
  });
  const OwnerId = IDL.Principal;
  const OwnershipRecord = IDL.Record({
    'purchaseTime' : Time,
    'owner' : OwnerId,
    'blueprintId' : IDL.Text,
  });
  const Progress = IDL.Record({
    'streak' : IDL.Nat,
    'goalWeight' : IDL.Float64,
    'currentWeight' : IDL.Float64,
    'checkpointsCompleted' : IDL.Nat,
  });
  const UserId = IDL.Principal;
  const Reaction = IDL.Record({
    'userId' : UserId,
    'reactionType' : IDL.Variant({
      'sad' : IDL.Null,
      'wow' : IDL.Null,
      'angry' : IDL.Null,
      'haha' : IDL.Null,
      'like' : IDL.Null,
      'love' : IDL.Null,
    }),
    'timestamp' : Time,
    'postId' : PostId,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const WeightEntry = IDL.Record({ 'weight' : IDL.Float64, 'date' : Time });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func([PostId, Comment], [], []),
    'addReaction' : IDL.Func(
        [
          PostId,
          IDL.Variant({
            'sad' : IDL.Null,
            'wow' : IDL.Null,
            'angry' : IDL.Null,
            'haha' : IDL.Null,
            'like' : IDL.Null,
            'love' : IDL.Null,
          }),
        ],
        [],
        [],
      ),
    'addReview' : IDL.Func([IDL.Text, Review], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createMarketplaceBlueprint' : IDL.Func([MarketplaceBlueprint], [], []),
    'createPost' : IDL.Func([Post], [], []),
    'createProjectBlueprint' : IDL.Func([ProjectBlueprintView], [], []),
    'deletePost' : IDL.Func([PostId], [], []),
    'followUser' : IDL.Func([IDL.Principal], [], []),
    'getBlueprint' : IDL.Func([], [IDL.Opt(Blueprint)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getComments' : IDL.Func([PostId], [IDL.Vec(Comment)], ['query']),
    'getDailyTasks' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(Time, DailyTask))],
        ['query'],
      ),
    'getFollowers' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'getMarketplaceBlueprint' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(MarketplaceBlueprint)],
        ['query'],
      ),
    'getMarketplaceBlueprints' : IDL.Func(
        [],
        [IDL.Vec(MarketplaceBlueprint)],
        ['query'],
      ),
    'getMessages' : IDL.Func([IDL.Text], [IDL.Vec(Message)], ['query']),
    'getOwnedBlueprints' : IDL.Func([], [IDL.Vec(OwnershipRecord)], ['query']),
    'getPost' : IDL.Func([PostId], [IDL.Opt(Post)], ['query']),
    'getPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getProgress' : IDL.Func([], [IDL.Opt(Progress)], ['query']),
    'getProjectBlueprints' : IDL.Func(
        [],
        [IDL.Vec(ProjectBlueprintView)],
        ['query'],
      ),
    'getReactions' : IDL.Func([PostId], [IDL.Vec(Reaction)], ['query']),
    'getReviews' : IDL.Func([IDL.Text], [IDL.Vec(Review)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWeightEntries' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(Time, WeightEntry))],
        ['query'],
      ),
    'initializeLikedBy' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'likePost' : IDL.Func([PostId], [], []),
    'purchaseBlueprint' : IDL.Func([IDL.Text], [], []),
    'saveBlueprint' : IDL.Func([Blueprint], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveDailyTask' : IDL.Func([Time, DailyTask], [], []),
    'saveProgress' : IDL.Func([Progress], [], []),
    'saveWeightEntry' : IDL.Func([WeightEntry], [], []),
    'sendMessage' : IDL.Func([IDL.Text, Message], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'unfollowUser' : IDL.Func([IDL.Principal], [], []),
  });
};

export const init = ({ IDL }) => { return []; };