/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Block {
  'id' : string,
  'content' : string,
  'order' : bigint,
  'blockType' : string,
  'options' : Array<string>,
}
export interface Blueprint {
  'id' : string,
  'theme' : BlueprintTheme,
  'active' : boolean,
  'createdAt' : Time,
  'calorieGoal' : number,
  'weeks' : bigint,
  'poundsToLose' : number,
}
export interface BlueprintTheme {
  'primaryColor' : string,
  'accentColor' : string,
  'bannerImage' : [] | [ExternalBlob],
  'secondaryColor' : string,
}
export interface Comment {
  'content' : string,
  'createdAt' : Time,
  'author' : string,
}
export type CreatorId = Principal;
export interface DailyTask {
  'waterIntake' : boolean,
  'date' : Time,
  'caloriesLogged' : boolean,
  'weighIn' : boolean,
  'stepsCompleted' : boolean,
  'workoutComplete' : boolean,
}
export type ExternalBlob = Uint8Array;
export interface MarketplaceBlueprint {
  'id' : string,
  'theme' : BlueprintTheme,
  'creator' : CreatorId,
  'createdAt' : Time,
  'tags' : Array<string>,
  'description' : string,
  'isFree' : boolean,
  'image' : [] | [ExternalBlob],
  'price' : bigint,
}
export interface Message {
  'content' : string,
  'sender' : string,
  'timestamp' : Time,
}
export type OwnerId = Principal;
export interface OwnershipRecord {
  'purchaseTime' : Time,
  'owner' : OwnerId,
  'blueprintId' : string,
}
export interface Post {
  'id' : PostId,
  'content' : string,
  'createdAt' : Time,
  'likedBy' : Array<Principal>,
  'author' : string,
  'likes' : bigint,
  'image' : [] | [ExternalBlob],
  'comments' : bigint,
  'attachedBlueprintId' : [] | [string],
}
export type PostId = string;
export interface Progress {
  'streak' : bigint,
  'goalWeight' : number,
  'currentWeight' : number,
  'checkpointsCompleted' : bigint,
}
export interface ProjectBlueprintView {
  'id' : string,
  'title' : string,
  'createdBy' : Principal,
  'steps' : Array<StepView>,
}
export interface Reaction {
  'userId' : UserId,
  'reactionType' : { 'sad' : null } |
    { 'wow' : null } |
    { 'angry' : null } |
    { 'haha' : null } |
    { 'like' : null } |
    { 'love' : null },
  'timestamp' : Time,
  'postId' : PostId,
}
export interface Review {
  'author' : string,
  'comment' : string,
  'timestamp' : Time,
  'rating' : bigint,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StepView {
  'id' : string,
  'order' : bigint,
  'name' : string,
  'blocks' : Array<Block>,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserId = Principal;
export interface UserProfile {
  'bio' : string,
  'username' : string,
  'completedTasks' : Array<Time>,
  'banner' : [] | [ExternalBlob],
  'followers' : bigint,
  'following' : bigint,
  'hasCompletedSetup' : boolean,
  'avatar' : [] | [ExternalBlob],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WeightEntry { 'weight' : number, 'date' : Time }
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[PostId, Comment], undefined>,
  'addReaction' : ActorMethod<
    [
      PostId,
      { 'sad' : null } |
        { 'wow' : null } |
        { 'angry' : null } |
        { 'haha' : null } |
        { 'like' : null } |
        { 'love' : null },
    ],
    undefined
  >,
  'addReview' : ActorMethod<[string, Review], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createMarketplaceBlueprint' : ActorMethod<[MarketplaceBlueprint], undefined>,
  'createPost' : ActorMethod<[Post], undefined>,
  'createProjectBlueprint' : ActorMethod<[ProjectBlueprintView], undefined>,
  'deletePost' : ActorMethod<[PostId], undefined>,
  'followUser' : ActorMethod<[Principal], undefined>,
  'getBlueprint' : ActorMethod<[], [] | [Blueprint]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getComments' : ActorMethod<[PostId], Array<Comment>>,
  'getDailyTasks' : ActorMethod<[], Array<[Time, DailyTask]>>,
  'getFollowers' : ActorMethod<[Principal], bigint>,
  'getMarketplaceBlueprint' : ActorMethod<
    [string],
    [] | [MarketplaceBlueprint]
  >,
  'getMarketplaceBlueprints' : ActorMethod<[], Array<MarketplaceBlueprint>>,
  'getMessages' : ActorMethod<[string], Array<Message>>,
  'getOwnedBlueprints' : ActorMethod<[], Array<OwnershipRecord>>,
  'getPost' : ActorMethod<[PostId], [] | [Post]>,
  'getPosts' : ActorMethod<[], Array<Post>>,
  'getProgress' : ActorMethod<[], [] | [Progress]>,
  'getProjectBlueprints' : ActorMethod<[], Array<ProjectBlueprintView>>,
  'getReactions' : ActorMethod<[PostId], Array<Reaction>>,
  'getReviews' : ActorMethod<[string], Array<Review>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWeightEntries' : ActorMethod<[], Array<[Time, WeightEntry]>>,
  'initializeLikedBy' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'likePost' : ActorMethod<[PostId], undefined>,
  'purchaseBlueprint' : ActorMethod<[string], undefined>,
  'saveBlueprint' : ActorMethod<[Blueprint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveDailyTask' : ActorMethod<[Time, DailyTask], undefined>,
  'saveProgress' : ActorMethod<[Progress], undefined>,
  'saveWeightEntry' : ActorMethod<[WeightEntry], undefined>,
  'sendMessage' : ActorMethod<[string, Message], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'unfollowUser' : ActorMethod<[Principal], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];