/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type OwnerId = Principal;
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export type PostId = string;
export interface Blueprint {
    id: string;
    theme: BlueprintTheme;
    active: boolean;
    createdAt: Time;
    calorieGoal: number;
    weeks: bigint;
    poundsToLose: number;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface BlueprintTheme {
    primaryColor: string;
    accentColor: string;
    bannerImage?: ExternalBlob;
    secondaryColor: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface StepView {
    id: string;
    order: bigint;
    name: string;
    blocks: Array<Block>;
}
export interface Post {
    id: PostId;
    content: string;
    createdAt: Time;
    likedBy: Array<Principal>;
    author: string;
    likes: bigint;
    image?: ExternalBlob;
    comments: bigint;
    attachedBlueprintId?: string;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface ProjectBlueprintView {
    id: string;
    title: string;
    createdBy: Principal;
    steps: Array<StepView>;
}
export interface Review {
    author: string;
    comment: string;
    timestamp: Time;
    rating: bigint;
}
export interface OwnershipRecord {
    purchaseTime: Time;
    owner: OwnerId;
    blueprintId: string;
}
export interface Comment {
    content: string;
    createdAt: Time;
    author: string;
}
export interface MarketplaceBlueprint {
    id: string;
    theme: BlueprintTheme;
    creator: CreatorId;
    createdAt: Time;
    tags: Array<string>;
    description: string;
    isFree: boolean;
    image?: ExternalBlob;
    price: bigint;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type CreatorId = Principal;
export type UserId = Principal;
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface Progress {
    streak: bigint;
    goalWeight: number;
    currentWeight: number;
    checkpointsCompleted: bigint;
}
export interface Message {
    content: string;
    sender: string;
    timestamp: Time;
}
export interface DailyTask {
    waterIntake: boolean;
    date: Time;
    caloriesLogged: boolean;
    weighIn: boolean;
    stepsCompleted: boolean;
    workoutComplete: boolean;
}
export interface Block {
    id: string;
    content: string;
    order: bigint;
    blockType: string;
    options: Array<string>;
}
export interface WeightEntry {
    weight: number;
    date: Time;
}
export interface UserProfile {
    bio: string;
    username: string;
    completedTasks: Array<Time>;
    banner?: ExternalBlob;
    followers: bigint;
    following: bigint;
    hasCompletedSetup: boolean;
    avatar?: ExternalBlob;
}
export interface Reaction {
    userId: UserId;
    reactionType: Variant_sad_wow_angry_haha_like_love;
    timestamp: Time;
    postId: PostId;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_sad_wow_angry_haha_like_love {
    sad = "sad",
    wow = "wow",
    angry = "angry",
    haha = "haha",
    like = "like",
    love = "love"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addComment(postId: PostId, comment: Comment): Promise<void>;
    addReaction(postId: PostId, reactionType: Variant_sad_wow_angry_haha_like_love): Promise<void>;
    addReview(blueprintId: string, review: Review): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createMarketplaceBlueprint(blueprint: MarketplaceBlueprint): Promise<void>;
    createPost(post: Post): Promise<void>;
    createProjectBlueprint(blueprint: ProjectBlueprintView): Promise<void>;
    deletePost(postId: PostId): Promise<void>;
    followUser(targetUser: Principal): Promise<void>;
    getBlueprint(): Promise<Blueprint | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getComments(postId: PostId): Promise<Array<Comment>>;
    getDailyTasks(): Promise<Array<[Time, DailyTask]>>;
    getFollowers(user: Principal): Promise<bigint>;
    getMarketplaceBlueprint(blueprintId: string): Promise<MarketplaceBlueprint | null>;
    getMarketplaceBlueprints(): Promise<Array<MarketplaceBlueprint>>;
    getMessages(conversationId: string): Promise<Array<Message>>;
    getOwnedBlueprints(): Promise<Array<OwnershipRecord>>;
    getPost(postId: PostId): Promise<Post | null>;
    getPosts(): Promise<Array<Post>>;
    getProgress(): Promise<Progress | null>;
    getProjectBlueprints(): Promise<Array<ProjectBlueprintView>>;
    getReactions(postId: PostId): Promise<Array<Reaction>>;
    getReviews(blueprintId: string): Promise<Array<Review>>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWeightEntries(): Promise<Array<[Time, WeightEntry]>>;
    initializeLikedBy(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    likePost(postId: PostId): Promise<void>;
    purchaseBlueprint(blueprintId: string): Promise<void>;
    saveBlueprint(blueprint: Blueprint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveDailyTask(date: Time, task: DailyTask): Promise<void>;
    saveProgress(userProgress: Progress): Promise<void>;
    saveWeightEntry(entry: WeightEntry): Promise<void>;
    sendMessage(conversationId: string, message: Message): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    unfollowUser(targetUser: Principal): Promise<void>;
}
import type { Blueprint as _Blueprint, BlueprintTheme as _BlueprintTheme, CreatorId as _CreatorId, ExternalBlob as _ExternalBlob, MarketplaceBlueprint as _MarketplaceBlueprint, Post as _Post, PostId as _PostId, Progress as _Progress, Reaction as _Reaction, StripeSessionStatus as _StripeSessionStatus, Time as _Time, UserId as _UserId, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addComment(arg0: PostId, arg1: Comment): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addComment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addComment(arg0, arg1);
            return result;
        }
    }
    async addReaction(arg0: PostId, arg1: Variant_sad_wow_angry_haha_like_love): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addReaction(arg0, to_candid_variant_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReaction(arg0, to_candid_variant_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async addReview(arg0: string, arg1: Review): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addReview(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReview(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createMarketplaceBlueprint(arg0: MarketplaceBlueprint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createMarketplaceBlueprint(await to_candid_MarketplaceBlueprint_n11(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMarketplaceBlueprint(await to_candid_MarketplaceBlueprint_n11(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createPost(arg0: Post): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createPost(await to_candid_Post_n16(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPost(await to_candid_Post_n16(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createProjectBlueprint(arg0: ProjectBlueprintView): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createProjectBlueprint(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProjectBlueprint(arg0);
            return result;
        }
    }
    async deletePost(arg0: PostId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePost(arg0);
            return result;
        }
    }
    async followUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.followUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.followUser(arg0);
            return result;
        }
    }
    async getBlueprint(): Promise<Blueprint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlueprint();
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlueprint();
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getComments(arg0: PostId): Promise<Array<Comment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getComments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getComments(arg0);
            return result;
        }
    }
    async getDailyTasks(): Promise<Array<[Time, DailyTask]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyTasks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyTasks();
            return result;
        }
    }
    async getFollowers(arg0: Principal): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowers(arg0);
            return result;
        }
    }
    async getMarketplaceBlueprint(arg0: string): Promise<MarketplaceBlueprint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMarketplaceBlueprint(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMarketplaceBlueprint(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMarketplaceBlueprints(): Promise<Array<MarketplaceBlueprint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMarketplaceBlueprints();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMarketplaceBlueprints();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMessages(arg0: string): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessages(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessages(arg0);
            return result;
        }
    }
    async getOwnedBlueprints(): Promise<Array<OwnershipRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOwnedBlueprints();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOwnedBlueprints();
            return result;
        }
    }
    async getPost(arg0: PostId): Promise<Post | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPost(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPost(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPosts(): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPosts();
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPosts();
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProgress(): Promise<Progress | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProgress();
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProgress();
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProjectBlueprints(): Promise<Array<ProjectBlueprintView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProjectBlueprints();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProjectBlueprints();
            return result;
        }
    }
    async getReactions(arg0: PostId): Promise<Array<Reaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReactions(arg0);
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReactions(arg0);
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReviews(arg0: string): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReviews(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReviews(arg0);
            return result;
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWeightEntries(): Promise<Array<[Time, WeightEntry]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWeightEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWeightEntries();
            return result;
        }
    }
    async initializeLikedBy(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeLikedBy();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeLikedBy();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async likePost(arg0: PostId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.likePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.likePost(arg0);
            return result;
        }
    }
    async purchaseBlueprint(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.purchaseBlueprint(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.purchaseBlueprint(arg0);
            return result;
        }
    }
    async saveBlueprint(arg0: Blueprint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveBlueprint(await to_candid_Blueprint_n47(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveBlueprint(await to_candid_Blueprint_n47(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n49(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n49(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveDailyTask(arg0: Time, arg1: DailyTask): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveDailyTask(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveDailyTask(arg0, arg1);
            return result;
        }
    }
    async saveProgress(arg0: Progress): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveProgress(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveProgress(arg0);
            return result;
        }
    }
    async saveWeightEntry(arg0: WeightEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveWeightEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveWeightEntry(arg0);
            return result;
        }
    }
    async sendMessage(arg0: string, arg1: Message): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1);
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async unfollowUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unfollowUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unfollowUser(arg0);
            return result;
        }
    }
}
async function from_candid_BlueprintTheme_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BlueprintTheme): Promise<BlueprintTheme> {
    return await from_candid_record_n22(_uploadFile, _downloadFile, value);
}
async function from_candid_Blueprint_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Blueprint): Promise<Blueprint> {
    return await from_candid_record_n20(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_MarketplaceBlueprint_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MarketplaceBlueprint): Promise<MarketplaceBlueprint> {
    return await from_candid_record_n32(_uploadFile, _downloadFile, value);
}
async function from_candid_Post_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Post): Promise<Post> {
    return await from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_Reaction_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Reaction): Reaction {
    return from_candid_record_n42(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n45(_uploadFile, _downloadFile, value);
}
async function from_candid_UserProfile_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): Promise<UserProfile> {
    return await from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Blueprint]): Promise<Blueprint | null> {
    return value.length === 0 ? null : await from_candid_Blueprint_n19(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n24(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): Promise<UserProfile | null> {
    return value.length === 0 ? null : await from_candid_UserProfile_n26(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MarketplaceBlueprint]): Promise<MarketplaceBlueprint | null> {
    return value.length === 0 ? null : await from_candid_MarketplaceBlueprint_n31(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Post]): Promise<Post | null> {
    return value.length === 0 ? null : await from_candid_Post_n35(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Progress]): Progress | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    theme: _BlueprintTheme;
    active: boolean;
    createdAt: _Time;
    calorieGoal: number;
    weeks: bigint;
    poundsToLose: number;
}): Promise<{
    id: string;
    theme: BlueprintTheme;
    active: boolean;
    createdAt: Time;
    calorieGoal: number;
    weeks: bigint;
    poundsToLose: number;
}> {
    return {
        id: value.id,
        theme: await from_candid_BlueprintTheme_n21(_uploadFile, _downloadFile, value.theme),
        active: value.active,
        createdAt: value.createdAt,
        calorieGoal: value.calorieGoal,
        weeks: value.weeks,
        poundsToLose: value.poundsToLose
    };
}
async function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    primaryColor: string;
    accentColor: string;
    bannerImage: [] | [_ExternalBlob];
    secondaryColor: string;
}): Promise<{
    primaryColor: string;
    accentColor: string;
    bannerImage?: ExternalBlob;
    secondaryColor: string;
}> {
    return {
        primaryColor: value.primaryColor,
        accentColor: value.accentColor,
        bannerImage: record_opt_to_undefined(await from_candid_opt_n23(_uploadFile, _downloadFile, value.bannerImage)),
        secondaryColor: value.secondaryColor
    };
}
async function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    username: string;
    completedTasks: Array<_Time>;
    banner: [] | [_ExternalBlob];
    followers: bigint;
    following: bigint;
    hasCompletedSetup: boolean;
    avatar: [] | [_ExternalBlob];
}): Promise<{
    bio: string;
    username: string;
    completedTasks: Array<Time>;
    banner?: ExternalBlob;
    followers: bigint;
    following: bigint;
    hasCompletedSetup: boolean;
    avatar?: ExternalBlob;
}> {
    return {
        bio: value.bio,
        username: value.username,
        completedTasks: value.completedTasks,
        banner: record_opt_to_undefined(await from_candid_opt_n23(_uploadFile, _downloadFile, value.banner)),
        followers: value.followers,
        following: value.following,
        hasCompletedSetup: value.hasCompletedSetup,
        avatar: record_opt_to_undefined(await from_candid_opt_n23(_uploadFile, _downloadFile, value.avatar))
    };
}
async function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    theme: _BlueprintTheme;
    creator: _CreatorId;
    createdAt: _Time;
    tags: Array<string>;
    description: string;
    isFree: boolean;
    image: [] | [_ExternalBlob];
    price: bigint;
}): Promise<{
    id: string;
    theme: BlueprintTheme;
    creator: CreatorId;
    createdAt: Time;
    tags: Array<string>;
    description: string;
    isFree: boolean;
    image?: ExternalBlob;
    price: bigint;
}> {
    return {
        id: value.id,
        theme: await from_candid_BlueprintTheme_n21(_uploadFile, _downloadFile, value.theme),
        creator: value.creator,
        createdAt: value.createdAt,
        tags: value.tags,
        description: value.description,
        isFree: value.isFree,
        image: record_opt_to_undefined(await from_candid_opt_n23(_uploadFile, _downloadFile, value.image)),
        price: value.price
    };
}
async function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PostId;
    content: string;
    createdAt: _Time;
    likedBy: Array<Principal>;
    author: string;
    likes: bigint;
    image: [] | [_ExternalBlob];
    comments: bigint;
    attachedBlueprintId: [] | [string];
}): Promise<{
    id: PostId;
    content: string;
    createdAt: Time;
    likedBy: Array<Principal>;
    author: string;
    likes: bigint;
    image?: ExternalBlob;
    comments: bigint;
    attachedBlueprintId?: string;
}> {
    return {
        id: value.id,
        content: value.content,
        createdAt: value.createdAt,
        likedBy: value.likedBy,
        author: value.author,
        likes: value.likes,
        image: record_opt_to_undefined(await from_candid_opt_n23(_uploadFile, _downloadFile, value.image)),
        comments: value.comments,
        attachedBlueprintId: record_opt_to_undefined(from_candid_opt_n37(_uploadFile, _downloadFile, value.attachedBlueprintId))
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userId: _UserId;
    reactionType: {
        sad: null;
    } | {
        wow: null;
    } | {
        angry: null;
    } | {
        haha: null;
    } | {
        like: null;
    } | {
        love: null;
    };
    timestamp: _Time;
    postId: _PostId;
}): {
    userId: UserId;
    reactionType: Variant_sad_wow_angry_haha_like_love;
    timestamp: Time;
    postId: PostId;
} {
    return {
        userId: value.userId,
        reactionType: from_candid_variant_n43(_uploadFile, _downloadFile, value.reactionType),
        timestamp: value.timestamp,
        postId: value.postId
    };
}
function from_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n37(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sad: null;
} | {
    wow: null;
} | {
    angry: null;
} | {
    haha: null;
} | {
    like: null;
} | {
    love: null;
}): Variant_sad_wow_angry_haha_like_love {
    return "sad" in value ? Variant_sad_wow_angry_haha_like_love.sad : "wow" in value ? Variant_sad_wow_angry_haha_like_love.wow : "angry" in value ? Variant_sad_wow_angry_haha_like_love.angry : "haha" in value ? Variant_sad_wow_angry_haha_like_love.haha : "like" in value ? Variant_sad_wow_angry_haha_like_love.like : "love" in value ? Variant_sad_wow_angry_haha_like_love.love : value;
}
function from_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n46(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
async function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MarketplaceBlueprint>): Promise<Array<MarketplaceBlueprint>> {
    return await Promise.all(value.map(async (x)=>await from_candid_MarketplaceBlueprint_n31(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Post>): Promise<Array<Post>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Post_n35(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Reaction>): Array<Reaction> {
    return value.map((x)=>from_candid_Reaction_n41(_uploadFile, _downloadFile, x));
}
async function to_candid_BlueprintTheme_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BlueprintTheme): Promise<_BlueprintTheme> {
    return await to_candid_record_n14(_uploadFile, _downloadFile, value);
}
async function to_candid_Blueprint_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Blueprint): Promise<_Blueprint> {
    return await to_candid_record_n48(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_MarketplaceBlueprint_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MarketplaceBlueprint): Promise<_MarketplaceBlueprint> {
    return await to_candid_record_n12(_uploadFile, _downloadFile, value);
}
async function to_candid_Post_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Post): Promise<_Post> {
    return await to_candid_record_n17(_uploadFile, _downloadFile, value);
}
async function to_candid_UserProfile_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): Promise<_UserProfile> {
    return await to_candid_record_n50(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    theme: BlueprintTheme;
    creator: CreatorId;
    createdAt: Time;
    tags: Array<string>;
    description: string;
    isFree: boolean;
    image?: ExternalBlob;
    price: bigint;
}): Promise<{
    id: string;
    theme: _BlueprintTheme;
    creator: _CreatorId;
    createdAt: _Time;
    tags: Array<string>;
    description: string;
    isFree: boolean;
    image: [] | [_ExternalBlob];
    price: bigint;
}> {
    return {
        id: value.id,
        theme: await to_candid_BlueprintTheme_n13(_uploadFile, _downloadFile, value.theme),
        creator: value.creator,
        createdAt: value.createdAt,
        tags: value.tags,
        description: value.description,
        isFree: value.isFree,
        image: value.image ? candid_some(await to_candid_ExternalBlob_n15(_uploadFile, _downloadFile, value.image)) : candid_none(),
        price: value.price
    };
}
async function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    primaryColor: string;
    accentColor: string;
    bannerImage?: ExternalBlob;
    secondaryColor: string;
}): Promise<{
    primaryColor: string;
    accentColor: string;
    bannerImage: [] | [_ExternalBlob];
    secondaryColor: string;
}> {
    return {
        primaryColor: value.primaryColor,
        accentColor: value.accentColor,
        bannerImage: value.bannerImage ? candid_some(await to_candid_ExternalBlob_n15(_uploadFile, _downloadFile, value.bannerImage)) : candid_none(),
        secondaryColor: value.secondaryColor
    };
}
async function to_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: PostId;
    content: string;
    createdAt: Time;
    likedBy: Array<Principal>;
    author: string;
    likes: bigint;
    image?: ExternalBlob;
    comments: bigint;
    attachedBlueprintId?: string;
}): Promise<{
    id: _PostId;
    content: string;
    createdAt: _Time;
    likedBy: Array<Principal>;
    author: string;
    likes: bigint;
    image: [] | [_ExternalBlob];
    comments: bigint;
    attachedBlueprintId: [] | [string];
}> {
    return {
        id: value.id,
        content: value.content,
        createdAt: value.createdAt,
        likedBy: value.likedBy,
        author: value.author,
        likes: value.likes,
        image: value.image ? candid_some(await to_candid_ExternalBlob_n15(_uploadFile, _downloadFile, value.image)) : candid_none(),
        comments: value.comments,
        attachedBlueprintId: value.attachedBlueprintId ? candid_some(value.attachedBlueprintId) : candid_none()
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    theme: BlueprintTheme;
    active: boolean;
    createdAt: Time;
    calorieGoal: number;
    weeks: bigint;
    poundsToLose: number;
}): Promise<{
    id: string;
    theme: _BlueprintTheme;
    active: boolean;
    createdAt: _Time;
    calorieGoal: number;
    weeks: bigint;
    poundsToLose: number;
}> {
    return {
        id: value.id,
        theme: await to_candid_BlueprintTheme_n13(_uploadFile, _downloadFile, value.theme),
        active: value.active,
        createdAt: value.createdAt,
        calorieGoal: value.calorieGoal,
        weeks: value.weeks,
        poundsToLose: value.poundsToLose
    };
}
async function to_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    username: string;
    completedTasks: Array<Time>;
    banner?: ExternalBlob;
    followers: bigint;
    following: bigint;
    hasCompletedSetup: boolean;
    avatar?: ExternalBlob;
}): Promise<{
    bio: string;
    username: string;
    completedTasks: Array<_Time>;
    banner: [] | [_ExternalBlob];
    followers: bigint;
    following: bigint;
    hasCompletedSetup: boolean;
    avatar: [] | [_ExternalBlob];
}> {
    return {
        bio: value.bio,
        username: value.username,
        completedTasks: value.completedTasks,
        banner: value.banner ? candid_some(await to_candid_ExternalBlob_n15(_uploadFile, _downloadFile, value.banner)) : candid_none(),
        followers: value.followers,
        following: value.following,
        hasCompletedSetup: value.hasCompletedSetup,
        avatar: value.avatar ? candid_some(await to_candid_ExternalBlob_n15(_uploadFile, _downloadFile, value.avatar)) : candid_none()
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_sad_wow_angry_haha_like_love): {
    sad: null;
} | {
    wow: null;
} | {
    angry: null;
} | {
    haha: null;
} | {
    like: null;
} | {
    love: null;
} {
    return value == Variant_sad_wow_angry_haha_like_love.sad ? {
        sad: null
    } : value == Variant_sad_wow_angry_haha_like_love.wow ? {
        wow: null
    } : value == Variant_sad_wow_angry_haha_like_love.angry ? {
        angry: null
    } : value == Variant_sad_wow_angry_haha_like_love.haha ? {
        haha: null
    } : value == Variant_sad_wow_angry_haha_like_love.like ? {
        like: null
    } : value == Variant_sad_wow_angry_haha_like_love.love ? {
        love: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
